services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: 'redis:5.0-alpine'
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  app-staging:
    container_name: app-staging
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

volumes:
  redis:
  postgres: