services:
  postgres-production:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $FRIENRADAR_DATABASE_USER
      POSTGRES_PASSWORD: $FRIENRADAR_DATABASE_PASSWORD
    ports:
      - "5432:5432"
    restart: always

  redis-production:
    container_name: redis
    restart: always
    image: 'redis:5.0-alpine'
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  app-production:
    container_name: app-production
    image: ghcr.io/luca-bruegger/frienradar-backend-production:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - myapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres-production
      - redis-production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-production.rule=Host(`api.frienradar.com`)"
      - "traefik.http.routers.app-production.entrypoints=websecure"

      - "traefik.http.services.app-production.loadbalancer.server.port=3000"

      - "traefik.http.routers.app-production.service=app-production"
      - "traefik.http.routers.app-production.tls.certresolver=le"
      - "traefik.http.routers.app-production.tls=true"


      - "traefik.http.routers.app-production-ws.rule=Host(`api.frienradar.com`)&&Path(`/cable`)"
      - "traefik.http.routers.app-production-ws.entrypoints=websecure"
      - "traefik.http.middlewares.redirect-production-wss.headers.customrequestheaders.X-Forwarded-Proto=https"

      - "traefik.http.routers.app-production-ws.service=app-production"
      - "traefik.http.routers.app-production-ws.tls.certresolver=le"



      - "traefik.http.middlewares.app-production.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD"
      - "traefik.http.middlewares.app-production.headers.accesscontrolalloworiginlist=https://app.frienradar.com,capacitor://app.frienradar.com"
      - "traefik.http.middlewares.app-production.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.app-production.headers.addvaryheader=true"
    environment:
      # General
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - DEVISE_JWT_SECRET_KEY=$DEVISE_JWT_SECRET_KEY
      - DEEPLINK_HOST=$DEEPLINK_HOST
      - RAILS_LOG_LEVEL=$RAILS_LOG_LEVEL
      - RAILS_APP_HOST=$RAILS_APP_HOST
      - RAILS_APP_HOSTS=$RAILS_APP_HOSTS
      - RAILS_SERVE_STATIC_FILES=$RAILS_SERVE_STATIC_FILES

      # Database
      - FRIENRADAR_DATABASE_PASSWORD=$FRIENRADAR_DATABASE_PASSWORD
      - FRIENRADAR_DATABASE_USER=$FRIENRADAR_DATABASE_USER
      - REDIS_URL=$REDIS_URL

      # ActionCable
      - ACTION_CABLE_URL=$ACTION_CABLE_URL
      - ACTION_CABLE_ALLOWED_REQUEST_ORIGINS=$ACTION_CABLE_ALLOWED_REQUEST_ORIGINS

      # OneSignal
      - ONESIGNAL_API_KEY=$ONESIGNAL_API_KEY
      - ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID
      - ONESIGNAL_USER_KEY=$ONESIGNAL_USER_KEY

      # Mailer
      - MAIL_DOMAIN_ADDRESS=$MAIL_DOMAIN_ADDRESS
      - MAIL_SMTP_PORT=$MAIL_SMTP_PORT
      - MAIL_EMAIL_ADDRESS=$MAIL_EMAIL_ADDRESS
      - MAIL_EMAIL_PASSWORD=$MAIL_EMAIL_PASSWORD

      # Hosts
      - CORS_ORIGINS=$CORS_ORIGINS

volumes:
  redis:
  postgres:
  myapp:

networks:
    default:
      name: base_default
      external: true