services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: frienradar
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: 'redis:5.0-alpine'
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - myapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - RAILS_MASTER_KEY=1558120081078cc63f9a1a343d518894

volumes:
  redis:
  postgres:
  myapp: