services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: frienradar
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: 'redis:5.0-alpine'
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      # Fake secrets for development
      - RAILS_MASTER_KEY=1558120081078cc63f9a1a343d518894
      - DEVISE_JWT_SECRET_KEY=5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_REQUEST_ORIGINS=/http:\/\/*/, /https:\/\/*/
      - ONESIGNAL_API_KEY=$ONESIGNAL_API_KEY
      - ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID
      - ONESIGNAL_USER_KEY=$ONESIGNAL_USER_KEY

  mailcatcher:
    image: yappabe/mailcatcher
    depends_on:
      - app-dev
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  redis:
  postgres: