services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $FRIENRADAR_DATABASE_STAGING_USER
      POSTGRES_PASSWORD: $FRIENRADAR_DATABASE_STAGING_PASSWORD
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: 'redis:5.0-alpine'
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  app-staging:
    container_name: app-staging
    image: ghcr.io/luca-bruegger/frienradar-backend:latest
    stdin_open: true
    tty: true
    volumes:
      - myapp:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-staging.rule=Host(`staging.api.frienradar.com`)"
      - "traefik.http.routers.app-staging.entrypoints=websecure"
      - "traefik.http.services.app-staging.loadbalancer.server.port=3001"
      - "traefik.http.routers.app-staging.service=app-staging"
      - "traefik.http.routers.app-staging.tls.certresolver=le"
      - "traefik.http.middlewares.app-staging.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD"
      - "traefik.http.middlewares.app-staging.headers.accesscontrolalloworiginlist=http://localhost:8100"
      - "traefik.http.middlewares.app-staging.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.app-staging.headers.addvaryheader=true"
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - FRIENRADAR_DATABASE_STAGING_PASSWORD=$FRIENRADAR_DATABASE_STAGING_PASSWORD
      - FRIENRADAR_DATABASE_STAGING_USER=$FRIENRADAR_DATABASE_STAGING_USER

volumes:
  redis:
  postgres:
  myapp:

networks:
    default:
      name: base_default
      external: true