development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: frienradar_development

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV["REDIS_URL_STAGING"] %>
  channel_prefix: frienradar_staging

production:
  adapter: redis
  url: <%= ENV["REDIS_URL_PRODUCTION"] %>
  channel_prefix: frienradar_production
