default: &default
  adapter: postgresql
  encoding: utf8
  host: postgres
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: frienradar_development

staging:
  <<: *default
  database: frienradar_staging

test:
  <<: *default
  database: frienradar_test

production:
  <<: *default
  database: Frienradar-backend_production
  username: frienradar
  password: <%= ENV['FRIENRADAR_DATABASE_PASSWORD'] %>

