default: &default
  adapter: postgresql
  encoding: utf8
  host: postgres
  pool: 5

development:
  <<: *default
  database: frienradar_development
  username: frienradar
  password: password

staging:
  <<: *default
  database: frienradar_staging
  username: <%= ENV['FRIENRADAR_DATABASE_USER'] %>
  password: <%= ENV['FRIENRADAR_DATABASE_PASSWORD'] %>
  port: <%= ENV['FRIENRADAR_DATABASE_PORT'] %>

test:
  <<: *default
  database: frienradar_test
  username: frienradar
  password: password

production:
  <<: *default
  database: frienradar_production
  username: <%= ENV['FRIENRADAR_DATABASE_USER'] %>
  password: <%= ENV['FRIENRADAR_DATABASE_PASSWORD'] %>

