default: &default
  adapter: postgresql
  encoding: utf8
  host: postgres
  pool: 5

development:
  <<: *default
  database: frienradar_development
  username: postgres
  password: password

staging:
  <<: *default
  database: frienradar_staging
  username: frienradar
  password: <%= ENV['FRIENRADAR_DATABASE_STAGING_PASSWORD'] %>

test:
  <<: *default
  database: frienradar_test
  username: postgres
  password: password

production:
  <<: *default
  database: Frienradar-backend_production
  username: frienradar
  password: <%= ENV['FRIENRADAR_DATABASE_PASSWORD'] %>

